VALIDATION_ANSWER_TYPE_YES = 'YES'
VALIDATION_ANSWER_TYPE_NO = 'NO'
VALIDATION_ANSWER_TYPE_NOT_SURE = 'NOT_SURE'

CATEGORIZATION_ANSWER_TYPE_NOT_SURE = 'NOT_SURE'

GENERAL_ANSWER_TYPE_NOT_SURE = 'NOT_SURE'

DISABLED_BUTTON = 'DISABLED_BUTTON'

CONFIRM_SUBMIT = 'CONFIRM_SUBMIT'
CONFIRM_START_OVER = 'CONFIRM_START_OVER'
CONFIRM_QUIT = 'CONFIRM_QUIT'