QUESTION_TYPE_TEXT = 0
QUESTION_TYPE_IMAGE = 1
QUESTION_TYPE_LOCATION = 2
QUESTION_TYPE_LOCATION_NAME = 3
QUESTION_TYPE_MULTIPLE_INPUT = 4
QUESTION_TYPE_SINGLE_VALIDATION_TEXT = 5
QUESTION_TYPE_SINGLE_VALIDATION_LOCATION = 6
QUESTION_TYPE_MULTIPLE_VALIDATION = 7

TEXT_BASED_QUESTION_TYPES = [QUESTION_TYPE_TEXT, QUESTION_TYPE_LOCATION_NAME, QUESTION_TYPE_MULTIPLE_INPUT]
SINGLE_VALIDATION_QUESTION_TYPES = [QUESTION_TYPE_SINGLE_VALIDATION_TEXT, QUESTION_TYPE_SINGLE_VALIDATION_LOCATION]