TASK_TYPE_CREATE_ITEM = 0
TASK_TYPE_VALIDATE_ITEM = 1
TASK_TYPE_CATEGORIZE_ITEM = 2
TASK_TYPE_ENRICH_ITEM = 3

TASK_TYPES_WITH_SELECTING_ITEMS = [TASK_TYPE_VALIDATE_ITEM, TASK_TYPE_CATEGORIZE_ITEM, TASK_TYPE_ENRICH_ITEM]